package com.vodacom.er.gui.actions;

public enum UserActions {
    LOGIN("LOGIN"),
    LOGOUT("LOGOUT"),
    SEARCHBYNAME("SEARCHBYNAME"),
    READALLNORMALUSERWITHGROUPS("READALLNORMALUSERWITHGROUPS"),
    READALLUSERFUNCTION("READALLUSERFUNCTION"),
    SEARCHGROUPFUNCTION("SEARCHGROUPFUNCTION"),
    SEARCHAUSER("SEARCHAUSER"),
    USERBYID("USERBYID"),
    ALLUSER("ALLUSER"),
    ALLUSERWITHPAGINATION("ALLUSERWITHPAGINATION"),
    CREATEUSERWITHGROUPLIST("CREATEUSERWITHGROUPLIST"),
    CREATEUSER("CREATEUSER"),
    CREATEUSERWITHSINGLEGROUP("CREATEUSERWITHSINGLEGROUP"),
    UPDATEUSERBYID("UPDATEUSERBYID"),
    UPDATEUSERBYGROUPLIST("UPDATEUSERBYGROUPLIST"),
    DELETEBYUSER("DELETEBYUSER"),
    DELETEUSERBYGROUP("DELETEUSERBYGROUP");

    private final String action;

    UserActions(String action) {
        this.action = action;
    }

    public String getAction() {
        return action;
    }
}

